travis:
  secure:
    BINSTAR_TOKEN: pPror0EPghdeNe7Ea25M1N38FW07JyLm+iaytPO/gfRC55Qw2iVCLi/apC72WkC5Sr/vh7bZUJ8nTW4ZVMZCesgvFo+IIk8tHp2/joEwiSTKc19ojY9biyLQqpV4zUQsdzDF87qEoilSkNKMqh8WC7RqLvsiXoxON8z7lmn4nD/XBqKaftUrwtYgEhbb3T7g4L40uUWIgThwTMLIqaEN5c9LhPiQisuum0c53+4xwFh8N2D5ZlO5YUnH+kVenJphZXT/XwIy6dRofjFBMKtR9vGB8gs2oRLc3tAunA3lHrFsULX3+GwzVWfB9PE+rMnnW4oy3zeEYbElXFfbUh1HN3CNHL14lx38cE+O8ajC7gDw3M+pFlbAYs9AUkKBk0fb8ZhyMLuSja6gaGC3yMfx+w4d9zo8BPTgAzEra9h8tv+G5G77etly5NRX39hTCt+m/znH9JVD58VVodAXoy2LY4/XCKabVg+Lc7nTtn1ZYm/iL2d9+rzGGRjdn0/YEseKpj9MIaxFntmmpuz6TGcuXdB+wCQgBeGN7yAKnFZIq34bALIvQ0SkDfBPOTxMFLVn6yHSSbtAO5cZvVfxtGg5I00YXaQ6Xan2074RRptG57ryP1dXSBSwqbaJKYFlpLBCjbrjf5hr/5sXMrV2rJasriIQ4GwiiyKEGUiSYccV4YE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
