travis:
  secure:
    BINSTAR_TOKEN: HVqEsVyKzd3FDIg0Xfa8znDektNwKADFLuwCjY+qXTSsfOH06pEpR5P6mOXtwSjP+ulArwYWp84zin5owDQjTGlde1x4uIOCDdR5Cmj4DW/cHt/MboRMe9YQdNnWHxqfQp8LCPnbBnxT304QCxTKnuacncuse9khu/cX5WZqUg4cA73QBEQG107sj1tDozEZajQVhd0qxjNUGa+ubg7lR9RMmgH1mXYuQ8ZKHzjk4yv3h5xsjqj8itoGsN+en+gPq2JVMJ+EOpRGbhHPPBerqR1rXuFGy8ivL4GqJuc9YZwmyD+XcMjO3JPF6hxRTy9Xyxof0WWQvGN+OZoCPjr11O0Mb8cfRCFolYyfIOeU48ty71fKpHStTiIt+0wJ6OQ5MOcrsHKzQWG36xQ78vFOBOp0nFYAJ3RIi7ugPgQFVhg0leqz0jsEzbv2PKlwQ+sLaDorGS2/X9FOr71QmfBgxxBwGZEgnBtZMgdrkNdpf3KLaGRBtqba96ocw1PgzHXEMjnVXRllMbTKOAQ5EGO/RDf9N0diCow5In9vEC5FztmOZxefyLQDD4K6GRjNdQS9zlcSpOecUwVmmUqHfUyVR1jmnVY3i6xU/WCPU2v2pr3hvPPkO32zZF0i1Flru5jnCvZXptfuJqkyuKD6tGgJIiDgAy3BK/QbVPCxioXK9Bw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
